datasources:
  default:
    ocid: ${ATP_OCID}
    wallet-password: ${ATP_WALLET_PASS:Micronaut2021}
    username: ${ATP_USER}
    password: ${ATP_PASSWORD}
    schema-generate: CREATE
    dialect: ORACLE
kafka:
  health:
    enabled: false
  bootstrap:
    servers: cell-1.streaming.${OCI_REGION:us-ashburn-1}.oci.oraclecloud.com:9092
  security:
    protocol: SASL_SSL
  sasl:
    mechanism: PLAIN
    jaas:
      config: org.apache.kafka.common.security.plain.PlainLoginModule required username="${OCI_STREAM_USER}" password="${OCI_STREAM_PASS}";        
micronaut:
  metrics:
    enabled: true
    export:
      oraclecloud:
        enabled: true
        applicationName: ${OCI_MONITORING_NAMESPACE:ocidemo}
        namespace: ${OCI_MONITORING_NAMESPACE}
        resourceGroup: ${OCI_MONITORING_RESOURCE_GROUP}      
tracing:
  zipkin:    
    enabled: true
    sampler:
      probability: 1
    http:
      url: https://${OCI_APM_AGENT_ID}.apm-agt.${OCI_REGION:us-ashburn-1}.oci.oraclecloud.com
      path: /20200101/observations/public-span?dataFormat=zipkin&dataFormatVersion=2&dataKey=${OCI_APM_KEY}
    supportsJoin: false           
oci:
  config:
    instance-principal:
        enabled: true    