micronaut:
  application:
    name: ocidemo
  router:
      static-resources:
          swagger:
              paths: classpath:META-INF/swagger
              mapping: /swagger/**        
  metrics:
    enabled: false              
datasources:
  default:
    url: jdbc:oracle:thin:@localhost:1521/xe
    driverClassName: oracle.jdbc.OracleDriver
    username: system
    password: oracle
    schema-generate: CREATE_DROP
    dialect: ORACLE
kafka:
  bootstrap:
    servers: localhost:9092
tracing:
  zipkin:
    enabled: true
    http:
      url: http://localhost:9411
    sampler:
      probability: 1                
        